# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Common_config = debug
  Engine_config = debug
  NetworkLibrary_config = debug
  ClientGame_config = debug
  ServerGame_config = debug
  Launcher_config = debug
  TestDemoGame_config = debug
  TestCommon_config = debug
  TestEngine_config = debug

else ifeq ($(config),release)
  Common_config = release
  Engine_config = release
  NetworkLibrary_config = release
  ClientGame_config = release
  ServerGame_config = release
  Launcher_config = release
  TestDemoGame_config = release
  TestCommon_config = release
  TestEngine_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Common Engine NetworkLibrary ClientGame ServerGame Launcher TestDemoGame TestCommon TestEngine

.PHONY: all clean help $(PROJECTS) DemoGame Tests

all: $(PROJECTS)

DemoGame: ClientGame Launcher ServerGame

Tests: TestCommon TestDemoGame TestEngine

Common:
ifneq (,$(Common_config))
	@echo "==== Building Common ($(Common_config)) ===="
	@${MAKE} --no-print-directory -C Common -f Makefile config=$(Common_config)
endif

Engine:
ifneq (,$(Engine_config))
	@echo "==== Building Engine ($(Engine_config)) ===="
	@${MAKE} --no-print-directory -C Engine -f Makefile config=$(Engine_config)
endif

NetworkLibrary:
ifneq (,$(NetworkLibrary_config))
	@echo "==== Building NetworkLibrary ($(NetworkLibrary_config)) ===="
	@${MAKE} --no-print-directory -C NetworkLibrary -f Makefile config=$(NetworkLibrary_config)
endif

ClientGame:
ifneq (,$(ClientGame_config))
	@echo "==== Building ClientGame ($(ClientGame_config)) ===="
	@${MAKE} --no-print-directory -C DemoGame -f ClientGame.make config=$(ClientGame_config)
endif

ServerGame:
ifneq (,$(ServerGame_config))
	@echo "==== Building ServerGame ($(ServerGame_config)) ===="
	@${MAKE} --no-print-directory -C DemoGame -f ServerGame.make config=$(ServerGame_config)
endif

Launcher: ClientGame ServerGame Common Engine NetworkLibrary
ifneq (,$(Launcher_config))
	@echo "==== Building Launcher ($(Launcher_config)) ===="
	@${MAKE} --no-print-directory -C DemoGame -f Launcher.make config=$(Launcher_config)
endif

TestDemoGame: ClientGame ServerGame Common Engine NetworkLibrary
ifneq (,$(TestDemoGame_config))
	@echo "==== Building TestDemoGame ($(TestDemoGame_config)) ===="
	@${MAKE} --no-print-directory -C TestDemoGame -f Makefile config=$(TestDemoGame_config)
endif

TestCommon: Common
ifneq (,$(TestCommon_config))
	@echo "==== Building TestCommon ($(TestCommon_config)) ===="
	@${MAKE} --no-print-directory -C test_common -f Makefile config=$(TestCommon_config)
endif

TestEngine: Common Engine
ifneq (,$(TestEngine_config))
	@echo "==== Building TestEngine ($(TestEngine_config)) ===="
	@${MAKE} --no-print-directory -C test_engine -f Makefile config=$(TestEngine_config)
endif

clean:
	@${MAKE} --no-print-directory -C Common -f Makefile clean
	@${MAKE} --no-print-directory -C Engine -f Makefile clean
	@${MAKE} --no-print-directory -C NetworkLibrary -f Makefile clean
	@${MAKE} --no-print-directory -C DemoGame -f ClientGame.make clean
	@${MAKE} --no-print-directory -C DemoGame -f ServerGame.make clean
	@${MAKE} --no-print-directory -C DemoGame -f Launcher.make clean
	@${MAKE} --no-print-directory -C TestDemoGame -f Makefile clean
	@${MAKE} --no-print-directory -C test_common -f Makefile clean
	@${MAKE} --no-print-directory -C test_engine -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Common"
	@echo "   Engine"
	@echo "   NetworkLibrary"
	@echo "   ClientGame"
	@echo "   ServerGame"
	@echo "   Launcher"
	@echo "   TestDemoGame"
	@echo "   TestCommon"
	@echo "   TestEngine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"