# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

RESCOMP = windres
INCLUDES += -Isrc -I../Common/src -I../Engine/src -I../NetworkLibrary/src -I../vendor/entt/include -I../vendor/json/include -I../vendor/sdl2/SDL2-2.30.1/include -I../vendor/sdl2/SDL2_image-2.8.2/include -I../vendor/sdl2/SDL2_mixer-2.8.0/include -I../vendor/sdl2/SDL2_ttf-2.22.0/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS +=
LDDEPS +=
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin
TARGET = $(TARGETDIR)/libServerGame_Debug.a
OBJDIR = obj/Debug/ServerGame
DEFINES += -D_HAS_EXCEPTIONS=0 -DDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wundef -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wundef -g -std=c++17
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64

else ifeq ($(config),release)
TARGETDIR = bin
TARGET = $(TARGETDIR)/libServerGame_Release.a
OBJDIR = obj/Release/ServerGame
DEFINES += -D_HAS_EXCEPTIONS=0
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wundef -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wundef -O2 -std=c++17
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s

endif

# Per File Configurations
# #############################################

PERFILE_FLAGS_0 = $(ALL_CXXFLAGS) -Werror

# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/InputState.o
GENERATED += $(OBJDIR)/InputStateFactory.o
GENERATED += $(OBJDIR)/health_component.o
GENERATED += $(OBJDIR)/json_configuration_loader.o
GENERATED += $(OBJDIR)/network_peer_global_component.o
GENERATED += $(OBJDIR)/player_aiming_controller.o
GENERATED += $(OBJDIR)/player_controller_component_configuration.o
GENERATED += $(OBJDIR)/player_movement_controller.o
GENERATED += $(OBJDIR)/player_network_entity_serialization_callbacks.o
GENERATED += $(OBJDIR)/player_rotation_controller.o
GENERATED += $(OBJDIR)/player_shooting_controller.o
GENERATED += $(OBJDIR)/player_state_configuration_utils.o
GENERATED += $(OBJDIR)/player_state_simulator.o
GENERATED += $(OBJDIR)/player_state_utils.o
GENERATED += $(OBJDIR)/pos_tick_network_system.o
GENERATED += $(OBJDIR)/pre_tick_network_system.o
GENERATED += $(OBJDIR)/server_dummy_input_handler_system.o
GENERATED += $(OBJDIR)/server_hit_registration_system.o
GENERATED += $(OBJDIR)/server_network_entity_creator.o
GENERATED += $(OBJDIR)/server_player_controller_system.o
GENERATED += $(OBJDIR)/server_player_simulation_events_processor.o
GENERATED += $(OBJDIR)/server_remove_death_entities_system.o
GENERATED += $(OBJDIR)/server_revive_death_players_system.o
GENERATED += $(OBJDIR)/server_world_initializer.o
GENERATED += $(OBJDIR)/simulation_events_handler.o
GENERATED += $(OBJDIR)/temporary_lifetime_objects_system.o
OBJECTS += $(OBJDIR)/InputState.o
OBJECTS += $(OBJDIR)/InputStateFactory.o
OBJECTS += $(OBJDIR)/health_component.o
OBJECTS += $(OBJDIR)/json_configuration_loader.o
OBJECTS += $(OBJDIR)/network_peer_global_component.o
OBJECTS += $(OBJDIR)/player_aiming_controller.o
OBJECTS += $(OBJDIR)/player_controller_component_configuration.o
OBJECTS += $(OBJDIR)/player_movement_controller.o
OBJECTS += $(OBJDIR)/player_network_entity_serialization_callbacks.o
OBJECTS += $(OBJDIR)/player_rotation_controller.o
OBJECTS += $(OBJDIR)/player_shooting_controller.o
OBJECTS += $(OBJDIR)/player_state_configuration_utils.o
OBJECTS += $(OBJDIR)/player_state_simulator.o
OBJECTS += $(OBJDIR)/player_state_utils.o
OBJECTS += $(OBJDIR)/pos_tick_network_system.o
OBJECTS += $(OBJDIR)/pre_tick_network_system.o
OBJECTS += $(OBJDIR)/server_dummy_input_handler_system.o
OBJECTS += $(OBJDIR)/server_hit_registration_system.o
OBJECTS += $(OBJDIR)/server_network_entity_creator.o
OBJECTS += $(OBJDIR)/server_player_controller_system.o
OBJECTS += $(OBJDIR)/server_player_simulation_events_processor.o
OBJECTS += $(OBJDIR)/server_remove_death_entities_system.o
OBJECTS += $(OBJDIR)/server_revive_death_players_system.o
OBJECTS += $(OBJDIR)/server_world_initializer.o
OBJECTS += $(OBJDIR)/simulation_events_handler.o
OBJECTS += $(OBJDIR)/temporary_lifetime_objects_system.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking ServerGame
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning ServerGame
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) del /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/server_player_simulation_events_processor.o: src/server/player_simulation/server_player_simulation_events_processor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/server_network_entity_creator.o: src/server/server_network_entity_creator.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/server_world_initializer.o: src/server/server_world_initializer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/server_dummy_input_handler_system.o: src/server/systems/server_dummy_input_handler_system.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/server_hit_registration_system.o: src/server/systems/server_hit_registration_system.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/server_player_controller_system.o: src/server/systems/server_player_controller_system.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/server_remove_death_entities_system.o: src/server/systems/server_remove_death_entities_system.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/server_revive_death_players_system.o: src/server/systems/server_revive_death_players_system.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/InputState.o: src/shared/InputState.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/InputStateFactory.o: src/shared/InputStateFactory.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/player_controller_component_configuration.o: src/shared/component_configurations/player_controller_component_configuration.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/health_component.o: src/shared/components/health_component.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/network_peer_global_component.o: src/shared/global_components/network_peer_global_component.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/json_configuration_loader.o: src/shared/json_configuration_loader.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/player_network_entity_serialization_callbacks.o: src/shared/player_network_entity_serialization_callbacks.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/player_aiming_controller.o: src/shared/player_simulation/player_aiming_controller.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/player_movement_controller.o: src/shared/player_simulation/player_movement_controller.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/player_rotation_controller.o: src/shared/player_simulation/player_rotation_controller.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/player_shooting_controller.o: src/shared/player_simulation/player_shooting_controller.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/player_state_configuration_utils.o: src/shared/player_simulation/player_state_configuration_utils.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/player_state_simulator.o: src/shared/player_simulation/player_state_simulator.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/player_state_utils.o: src/shared/player_simulation/player_state_utils.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/simulation_events_handler.o: src/shared/player_simulation/simulation_events_handler.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pos_tick_network_system.o: src/shared/systems/pos_tick_network_system.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pre_tick_network_system.o: src/shared/systems/pre_tick_network_system.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/temporary_lifetime_objects_system.o: src/shared/systems/temporary_lifetime_objects_system.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(PERFILE_FLAGS_0) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif